version: '3'

services:
  web:
    container_name: web
    build: ./docker
    ports:
      - 80:80
    privileged: true
    volumes:
      - ./src:/var/www/html

  database:
    image: mysql
    container_name: database-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/my.cnf:/etc/mysql/conf.d/my.cnf
      #- ./docker/database/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=database-host
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80